version: '3.5'

networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true
  g04-warehouse-service_internal:
    name: g04-warehouse-service_internal
    external: false

services:

  app:
    image: $CICD_IMAGE_ID
    environment:
      - 'MICRONAUT_APPLICATION_NAME=g04-warehouse-service'
      - 'MICRONAUT_SERVER_PORT=8096'
      - 'RABBITMQ_URI=amqp://bus:5672'
      - 'RABBITMQ_USERNAME=swda'
      - 'RABBITMQ_PASSWORD=swda'
      - 'MONGODB_URI=mongodb://warehouse-mongodb:27017/warehouse-db'
      - 'MONGODB_PACKAGE_ENTITIES=ch.hslu.swda.data.entities'
    networks:
      - bus
      - ingress
      - g04-warehouse-service_internal
    deploy:
      replicas: 1
      labels:
        # - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`${CI_PROJECT_NAME}.${TLD}`)"
        - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`www.${TLD}`) && PathPrefix(`/api/warehouse`)"
        - "traefik.http.services.${CICD_STACK_NAME}App.loadbalancer.server.port=8096"
        - 'traefik.http.routers.${CICD_STACK_NAME}App.entrypoints=websecure'
        - 'traefik.http.routers.${CICD_STACK_NAME}App.tls.certresolver=letsencrypt'

  warehouse-mongodb:
    image: cr.gitlab.switch.ch/hslu/shared/devops/docker-cache/bitnami/mongodb:4.2.19
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: 'root'
    #      MONGO_INITDB_ROOT_PASSWORD: 'root'
    networks:
      - g04-warehouse-service_internal
    deploy:
      replicas: 1
