micronaut:
  application:
    name: ${MICRONAUT_APPLICATION_NAME:g04-warehouse-service}
  server:
    port: ${MICRONAUT_SERVER_PORT:8090}
    context-path: /api/warehouse
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths:
          - classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths:
          - classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths:
          - classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      swagger-ui-res:
        paths:
          - classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /res/**
    data:
      mongodb:
        create-collections: true
rabbitmq:
  uri: ${RABBITMQ_URI:amqp://bus:5672}
  username: ${RABBITMQ_USERNAME:swda}
  password: ${RABBITMQ_PASSWORD:swda}
mongodb:
  uri: ${MONGODB_URI:mongodb://mongodb:27017/warehouse-db}
  package-names:
    - ${MONGODB_PACKAGE_ENTITIES:ch.hslu.swda.data.entities}