version: '3.5'

networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true
  inventory-internal:
    name: inventory-internal
    external: false

services:

  app:
    image: $CICD_IMAGE_ID
    environment:
      - 'MICRONAUT_APPLICATION_NAME=g04-inventory-service'
      - 'MICRONAUT_SERVER_PORT=8095'
      - 'RABBITMQ_URI=amqp://bus:5672'
      - 'RABBITMQ_USERNAME=swda'
      - 'RABBITMQ_PASSWORD=swda'
      - 'MONGODB_URI=mongodb://inventory-mongodb:27017/inventory-db'
      - 'MONGODB_PACKAGE_ENTITIES=ch.hslu.swda.api.entities'
    networks:
      - bus
      - ingress
      - inventory-internal
    deploy:
      replicas: 1
      labels:
        - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`www.${TLD}`) && PathPrefix(`/api/inventory`)"
        - "traefik.http.services.${CICD_STACK_NAME}App.loadbalancer.server.port=8095"
        - 'traefik.http.routers.${CICD_STACK_NAME}App.entrypoints=websecure'
        - 'traefik.http.routers.${CICD_STACK_NAME}App.tls.certresolver=letsencrypt'

  inventory-mongodb:
    image: cr.gitlab.switch.ch/hslu/shared/devops/docker-cache/bitnami/mongodb:4.2.19
    networks:
      - inventory-internal
    deploy:
      replicas: 1
